project:
  type: website
  output-dir: docs

website:
  title: "CIFI"
  navbar:
    left:
      - href: scg.qmd
        text: SCG
      - href: fse.qmd
        text: FSE

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



