---
title: "CIFI Methodology for Stock Corporations: The GROCO"
format: html
date: 2025-12-27
author: Alex Stomper
affiliation: Humboldt University, Berlin
---

## Measuring Value from Growth: Motivation

Which type of governance problems present themselves when we think about a particular corporation? This depends on the nature of the corporation and the situation it's in. Is is a growing firm or a mature business? What potential is there for growth in the firm's existing lines of business? What potential for growth due to new lines of business? Should a firm pay out its profits or invest them to use growth opportunities? Would such investments earn some extra expected return ("alpha") over the cost of tying up capital?

One way to approach these questions is based on classifying firms based on the extent to which growth opportunities drive firm value. This document presents a methodology for estimating the growth component of stock prices (GROCO).

The GROCO is not only relevant for shareholders. Firms with low GROCO can provide a stable foundation for economic development while those with high GROCO are often involved in developments that are not yet well understood but may turn out to drive change.

## Measuring value from growth: Theory

For a firm with a low probability of bankruptcy, the value of growth opportunities should add similarly to firm value and to equity value. It is, therefore, common to measure the value of a firm's growth opportunities (VGO) as the difference between the value of its equity (VE) and that of all cash flows its shareholders earn from assets-in-place:
$$VGO=VE-VA.$$

How can we actually measure the VGO? We want to come up with measures that are transparent and use only publicly available data from platforms like Morningstar or Yahoo Finance.

### Book value of equity vs. market value
$$VGO=VE-VA.$$
This implies the following measure of the degree to which growth opportunities drive equity value:
$$\frac{VGO}{VE}=1-\frac{VA}{VE}.$$

A crude proxy for the ratio on the right-hand side is the ratio of the book value of a firm's equity to its market value or book value per share (BPS) relative to the stock price P. This measure, however, equates the value of a firm's assets-in-place to their book value which may be a poor proxy for their market value.

### Measures based on earnings yields

Better measures of the importance of growth opportunities come from a break-even condition that equates the opportunity cost of investing in a firm's stock to the expected return:
$$\bar r P=E[DIV]+\bar g P,$$
where the left-hand side is the product of the stock price and an expected return that could have been earned in investments with similar risk and right-hand side is the expected payoff of investing in the stock, - the sum of an expected dividend and capital gain (or loss) specified in terms of an expected growth rate of the stock price, g. The bar over g and r marks these as expected values.

We will specify the expected dividend in terms of earnings-per-share (EPS). EPS is the maximum dividend a firm could pay without selling some assets or raising some funding from external sources.

### A benchmark

In reality, dividends are typically below earnings-per-share (EPS) because firms "retain" earnings. A useful benchmark result comes from thinking about a fully equity-financed firm whose earnings retention funds investments in growth opportunities in existing (rather than new) lines of business. In this case, the break-even condition reads:
$$\bar r_{A} P=(1-b)E[EPS]+\bar g_{A}(b) P,$$ 
where the A-subscripts highlight that the expected return and growth comes from assets like the assets-in-place supporting the existing lines of business. b is the rate of earnings retention ("plowback", (EPS-DIV)/EPS) which determines the dividend (DIV) and the capital gain (or loss) rate:
$$DIV=(1-b)EPS, \bar g_{A}=b ROI,$$
where ROI is a return-on-investment, assumed to be constant. 

### The earings yield from plowback (EYP)

The last version of the break-even condition implies an expression for the earnings yield, - the ratio of projected earnings-per-share to the stock price:
$$\frac{E[EPS]}{P}=\frac{\bar r_{A}-b ROI}{1-b}.$$
We next define the return on reinvested earnings as the sum of the cost of capital and some "extra" expected return, denoted as alpha:
$$ROI=\bar r_{A}+\alpha.$$
By substituting the expression into the previous one, we obtain the following definition of the earnings yield from plowback, - the plowback yield (PY):
$$PY=\bar r_{A} -\frac{b}{1-b}\alpha.$$

### A benchmark stock price

What stock price results from the last version of the break-even condition? It is, of course, the ratio of expected earnings-per-share and the plowback yield (PY). The actual stock price will differ from this benchmark due to the per-share value of cash flows from growth opportunities other than those unlocked by re-investing earnings in a firm's existing lines of business. This value component is represented by the last term of the following expression:
$$P=\frac{E[EPS]}{PY}+VGOPS.$$
This yields a way of measuring the growth component (GROCO) of a stock price:
$$GROCO=\frac{VGOPS}{P}=1-\frac{E[EPS]/P}{PY}.$$
The GROCO is one minus a firm's earnings yield divided by its plowback yield.

The remainder of this document explains how to actually measure the GROCO.

### Implementation

A basic measure of the GROCO results from the following specification:
$$PY=\bar r_{A}.$$
This is a baseline case with zero "alpha". It highlights that the PY equals costs of tying up capital in firms' assets-in-place: cost of capital (CoC). 

It is tempting to measure CoC using expected stock returns (investors' compensation for CoC), but the underlying market expectations involve not only a firm's assets in place, but also its growth options.

To focus on information about firms' assets-in-place only, we can use accounting data, exploiting the backward-looking nature of these data (similar to the approach in Cao, Simin and Zhao (2008)).

### Data

Accounting data allow for measuring firm-level returns on invested capital (ROIC). ROICs contain information about cost of capital since they result from investment decisions in which investment returns were expected to exceed hurdle rates govering firms' capital allocation processes. This suggests the following specification:
$$PY=h_{A}-\kappa,$$
where the right-hand side is a cost of capital, specified as the difference between a hurdle ROIC and a "kappa" by which the ROIC exceeds the cost of capital. This kappa can be interpreted as a measure of conservatism: It specifies a minimum profit margin below which growth opportunities are ignored.

Here is a [website](costofcapital.org) comparing the hurdle/discount rates that firms use to their (perceived) cost of capital. For Germany, this suggests a kappa of 3 percent. 

### Parameterization

The previous specification uses the kappa not only to account for corporate conservatism, but also for absorbing deviations of observed ROIs from hurdle rates govering firms' capital allocation processes as lower bounds for investments' expected ROIs. A higher value of kappa should, therefore, be used when ROIC appears artificially high and also when there is more variation in ROIC across business years.

The parameters alpha and b can be used to more specifically model a firm's future value creation from earnings retention:
$$EYP(b,\alpha)=(ROI_{OBS}-\kappa) -\frac{b}{1-b}\alpha.$$
A baseline approach would set alpha equal to kappa and use a plowback rate b equal to one minus an observed payout ratio (DIV/EPS).

### Summary

1. Measure expected return from reinvesting earnings, using accounting data. In an example below, we do so using a return on incremental invested capital (ROIIC). 
2. Pick a value of kappa to account for differences between observed returns and costs of capital. 
3. Compute the plowback yield (PY) using the basic approach. Or take a further step and compute the PY for some alpha and plowback rate b.
2. Take the inverse of a firm's price-earnings (PE) ratio. This is its earnings yield (EY).
3. Compute the growth component of the stock price as one minus the EY divided by the PY.

Wait. PY was defined for a fully equity-financed firm. What if a firm is partly debt-financed? Is it legitimate to compare such a firm's earnings yield to its PY?

We need another implementation step...

### The zero-debt earnings yield (EY0)

Appendix E of of Koller et al. (2005) analyzes the effect of debt financing on price-earnings (PE) ratios. The result can be re-stated to interpret observed earnings yields (inverse PE ratios) as resulting from zero-debt earnings yields and a cost of debt financing:
$$EY=EY_0+(EY_0-\bar r_D)\frac{DV}{EV},$$
where the fraction on the right-hand side is the ratio of debt-to-equity value, which multiplies the difference between a zero-debt earnings yield (EY0) and a cost of debt capital. This difference is typically positive. If so, 
$$EY_0=\frac{DV}{EV+DV}\bar r_D+\frac{EV}{EV+DV}EY.$$
If EY0 comes out lower than the observed EY, it is conservative to estimate GROCO using the cost of debt financing.

### More data requirements

1. Leverage. Computing the zero-debt earnings yield requires a measure of leverage and the cost of debt capital. Yahoo finance reports "Total Debt/Equity" for the most recent quarter (mrq). To compute leverage as the ratio of total debt (DV) to firm value (DV plus EV), divide the debt-equity ratio by 1 plus itself.

2. Cost of debt capital. Here, the most straightforward measure is the yield of a corporate bond issued by the firm whose GROCO we want to measure. An alternative measure is based on the firm's rating and yields of bonds with such a rating. If no rating is available, one can construct a synthetic rating using the firm's interest coverage ratio.

## Summary

1. Estimate the plowback yield PY.
2. Estimate the zero-debt earnings yield EY0.
3. Compute the growth component of the stock price:
$$GROCO=1-\frac{EY0}{PY}.$$
4. Robustness analyses for different values of kappa, alpha and the future plowback rate b. 

The rest of this document provides an illustration of the above-stated approach, measuring the GROCO of Microsoft. This illustration will also introduce some finer points regarding the approach and, in particular, the measurement of a firm's cost of capital using (mostly) accounting data.

### Microsoft: NOPAT

We first compute a measure of Microsoft's return on incremental invested capital (ROIIC) between the years 2023 (as reference year) and 2025 (the most recent year, at the time of writing). This requires dividing a change in net operating income after taxes (NOPAT) by a change in invested capital. 
 
To estimate NOPAT, we need a tax rate which we estimate as the ratio of pre-tax income and an income tax paid or tax provision. Using data from Yahoo Finance about Microsoft's Income Statement for 2025, the tax rate estimate is 21,795/123,627 and operating income is 128,528,000. Our estimate for NOPAT is:
$$NOPAT_{2025}=128,528,000\left(1-\frac{21,795}{123,627}\right)=105,869,000.$$
The NOPAT estimate for 2023 is 71,226,000.

### Microsoft: Invested capital and ROIIC

Invested capital can be found in the balance sheet data on Yahoo Finance. For 2022, it was 216,323,000 and it was 320,107,000 for 2024. This implies a return on incremental invested capital (ROIIC) of 33 percent:
$$ROIIC_{2023,2025}=\frac{105,869,000-71,226,000}{320,107,000-216,323,000}=\frac{34,643,000}{103,784,000}=0.33.$$

This ROIIC is certainly high, given that the return on the market portfolio is about 10 percent. How anticipated was this "outperformance"? Put differently, what would be the hurdle rate to which the ROIIC would have been compared in measuring outperformance? 

### Microsoft: Hurdle rate

We now use the outperformance of Microsoft's stock to isolate an unanticipated component of the ROIIC. 

Microsoft reports on June 30 of each year. What was its total return between this date of 2023 and 2025? According to [totalrealreturns.com](https://totalrealreturns.com), it was a return of 48 percent.

Yahoo Finance reports a total debt-to-equity ratio of 33 percent for 2025. Assuming this level of leverage for the entire period from 2023-2025 means that, corrected for leverage, the performance was 36 percent (48 percent divided by 1.33) or about 17 percent per annum. 

If 8 percent of this was outperformance (against an expected return of the US market portfolio of about 9 percent), the ROIIC would imply a hurdle rate of 25 percent (33 minus 8).  

### Microsoft: Kappa

[Gormes and Huber (2025)](https://www.aeaweb.org/articles?id=10.1257/aer.20231246) find that hurdle rates increase by 0.7-1.1 percentage points per percentage point of cost of capital. If the cost of capital were that of the market portfolio (about 9 percent), a hurdle rate of 25 percent would contain the following kappa:
$$\kappa = 0.9(0.25-0.09)=0.14,$$
where the term in parantheses is the difference between the hurdle rate and the expected return of the US market portfolio. With this benchmark, the estimate for kappa is not contaminated by data coming from market expectations about Microsoft's use of its growth opportunities. An alternative benchmark would be the actual return of the market portfolio (between June 30 2023 and 2025), but this return would be too correlated with that of Microsoft's stock. 

Given a kappa of 14 percent, the perceived cost of capital of Microsoft should be 11 percent (25 minus 14).

### Microsoft: GROCO

We use the basic approach, setting alpha to zero, so that the plowback yield is:
$$PY=0.11.$$

At the time of writing, Yahoo Finance reports a forward price-earnings (PE) ratio of about 30, so that its observed earnings yield is 3.3 percent. We next compute the zero-debt earnings yield, starting with the cost of debt financing: Microsoft's corporate bond with a maturity of 10 years shows a yield of about 4.5 percent. 

This is higher than the 3.3 percent, so that the zero-debt yield would be above the observed earnings yield. We, therefore, compute a conservative estimate of GROCO using the 4.5 percent in place of the EY0:
$$GROCO=1-\frac{0.045}{0.11}=0.59.$$

### Microsoft 

Microsoft's stock price contains a substantial GROCO of 59 percent. This estimate is conservative, provided the ROIIC's outperformance component has not been over-estimated at 8 percent, so that a hurdle rate of 25 percent is not too low relative to the ROIIC estimate (33 percent). 

Microsoft appears to be one of the firms whose actions will widely matter for society in the US and abroad. We need to understand how Microsoft uses its growth opportunities and whether it acts in shareholders' interest, taking into account that shareholders also have non-pecuniary interests, - for example concerning responsible development of AI. 

### More general take-aways from analyzing Microsoft

We have seen one approach for setting the value of kappa and estimating the plowback yield PY:

1. Compute the return on incremental invested capital (ROIIC).
2. Adjust the result by subtracting the outperformance implied by the outperformance of the firm's stock, taking into account that leverage will magnify this outperformance. The adjustment yields a proxy for the hurdle rate h the firm uses in investment decisions.
3. We use the difference between h and the expected return of the market porfolio to specify a value for the kappa:
$$\kappa=f(h-\bar r_M),$$
where we used f=0.9.
4. Subtracting the kappa from h yields a baseline value for the EYP.