---
title: "Citizenship and Finance (CIFI)"
---

Welcome to the homepage of the CIFI initiative. 

This initiative aims to develop and apply a citizen science methodology focused on governance issues with a financial perspective. It prioritizes transparency and accessibility, requiring only modest data inputs, limited to freely and publicly available data sources.

Use the navbar to navigate to different topics of the initiative. For regular updates, subscribe to the CIFI substack:

<iframe src="https://cifi.substack.com/embed" width="480" height="320" style="border:1px solid #EEE; background:white;" frameborder="0" scrolling="no"></iframe>

**Topics:**

- **Fiscal space exploration (FSE):** Methods for analyzing sovereign default risk and the sustainability of public finances. Fiscal space is a government's ability to fund new priorities while maintaining the confidence of creditors that the government can meet its obligations to them.

- **Seperatist corporate governance (SCG):** Here, the title alludes to the fact that corporate governance is currently mostly based on the idea of [Friedman separation](https://www.promarket.org/2020/10/13/milton-friedman-legacy-doctrine-theorem/), - that shareholders' interest in financial value creation can be separated from other - more "public" - interests of shareholders. The branch contains methods for analyzing issues in corporate governance.
